default: true

MD001: false #Heading style - Allow heading levels to be incremented by multiple levels at a time
MD013: false #Line length - https://github.com/DavidAnson/markdownlint/blob/HEAD/doc/Rules.md#md013
MD033: false #Inline HTML - https://github.com/DavidAnson/markdownlint/blob/HEAD/doc/Rules.md#md033
MD024:
  siblings_only: true #Multiple headers with the same content
