name: Verify HTML

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0 # keep in sync with 'engines'@package.json
      - name: Install Dependencies
        run: npm install
      - name: Build Site
        run: npm run build

      - uses: actions/cache@v3
        with:
          path: tmp/.htmltest
          key: ${{ runner.os }}-htmltest

      - name: Install htmltest
        run: curl https://htmltest.wjdp.uk | bash

      - name: Verify HTML links
        env:
          HTMLTEST_CONFIG: .github/config/htmltest.yml
        run: |
          ./bin/htmltest 
