name: Test verify-html dispatch
# Workflow Update OCM CLI Docs now has two triggers:
# 1. pull_request: branches: main
# 2. workflow_dispatch: pr_number
# since workflows of kind pull_request are not triggered by the GITHUB_TOKEN
# we need to dispatch the verify-html workflow in case it is triggered from 
# workflow "Update OCM CLI Docs" using the GITHUB_TOKEN

permissions:
  contents: read          # for checkout, file reads
  actions: write          # to call repository_dispatch
  pull-requests: write    # to create or update PRs

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to test'
        required: true

jobs:
  fire-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Get OCMBot installation token
        # The dispatch event needs to be triggered with the OCMBot GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.OCMBOT_APP_ID }}
          private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
      
      - name: Dispatch verify-html
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          # IMPORTANT: use the App token, not GITHUB_TOKEN
          token: ${{ steps.app_token.outputs.token }}
          event-type: verify-html
          client-payload: '{ "pr_number": "${{ github.event.inputs.pr_number }}" }''
