name: Update security.txt

on:
  schedule:
    # Job runs on eversy Monday in December at 00:00 UTC
    - cron: '0 0 * 12 1'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
            app_id: ${{ secrets.OCMBOT_APP_ID }}
            private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
            
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Fetch security.txt
      run: |
        curl https://github.tools.sap/sgsc-engineering-and-automation/securitytxt/raw/main/security.txt -o static/.well-known/security.txt

    - name: Commit and push if it has been changed
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update security.txt"
        git push