name: Markdown

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Lint Markdown
    steps:
      - uses: actions/checkout@v4
      - name: Markdown Linting
        uses: nosborn/github-action-markdown-cli@v3
        with:
          files: .
          dot: true
          config_file: .github/config/markdownlint.yml
          ignore_path: .github/config/markdownignore
  verify-links:
    name: Verify HTML links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      - name: Install Dependencies
        run: npm install
      - name: Build Site
        run: npm run build
      - name: Verify HTML links
        uses: untitaker/hyperlink@0.1.32
        with:
          args: public/ --sources content/
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: .github/config/spellcheck.yml
          task_name: Markdown
